### ISSUE TITLE
(FIX FOUND) Tags in tk.Text are not deleted in HTMLScrolledText.set_html()

### ISSUE THREAD

**Issue by valeriy-chepelev** [bauripalash/tkhtmlview#10]
deleted, see below

**Comment by valeriy-chepelev** [comment]
### FIX FOUND

Tags in tk.Text are not deleted in HTMLScrolledText.set_html():

```
self.tag_delete(self.tag_names)
# can't work because no ()

self.tag_delete(self.tag_names())
# look like didn't work :(

for tag in self.tag_names(): self.tag_delete(tag)
# works fine, closes an issue
```

Author, pls commit.

**Comment by bauripalash** [comment]
Send PR

**Comment by nirajpoudel** [comment]
Error while installing. [](url
![Screenshot from 2021-11-20 10-02-15](https://user-images.githubusercontent.com/59787504/142714120-ac7b0367-5261-4491-9fd0-282c8c18d47e.png)
)

**Comment by bauripalash** [comment]
I am working on this now.

**Comment by bauripalash** [comment]
Fixed via https://github.com/bauripalash/tkhtmlview/commit/dcab4604dda86305418dca78a018ed14ade62cb1
