### ISSUE TITLE
Package on PyPI not updated with recent typo fixes.

### ISSUE THREAD

**Issue by AntonisTorb** [bauripalash/tkhtmlview#23]
Hi there, love this package!

It seems the "BACKGROUD" typo fixes have not been pushed to the PyPI package yet, so installing the package via pip introduces errors when running.

If anyone is facing the same issue, until the package is updated, you can do the following on a Windows PC (not sure about other OS):

## If you are using a virtual environment:
- navigate to \env\Lib\site-packages\tkhtmlview in your project folder
- open html_parser.py
- edit lines 359, 360 replacing "BACKGROUD" with "BACKGROUND" and save the file

## If you are not using a virtual environment:
- navigate to \~your_user_folder\AppData\Local\Programs\Python\~your_Python_version\Lib\site-packages\tkhtmlview
- open html_parser.py
- edit lines 359, 360 replacing "BACKGROUD" with "BACKGROUND" and save the file

Once the package has been updated feel free to close this issue. 

Thanks again for the awesome work!

**Comment by bauripalash** [comment]
I have updated the PyPi package.

https://pypi.org/project/tkhtmlview/0.1.1.post1/

**Comment by AntonisTorb** [comment]
Thank you!
