### ISSUE TITLE
ModuleNotFoundError while installing

### ISSUE THREAD

**Issue by adsau59** [bauripalash/tkhtmlview#3]
I had tkhtmlview as a dependency for my application (fishy), some people are getting ModuleNotFoundError for requests and PIL while installing using pip

for now, I just removed your library as a dependency and manually copied your code in my codebase, which I don't mind, just thought u should know that there is this issue

the strange thing is, i wasn't able to reproduce the issue, but multiple people were getting the same issue.

How to reproduce?
1) install new python 3.7.3
2) pip install fishy==0.3.3

Workaround:
1) run `pip install Pillow requests` before installing fishy

![](https://cdn.discordapp.com/attachments/557122745931005967/712413574001065994/2020-05-20_00h16_55.png)

![](https://cdn.discordapp.com/attachments/557122745931005967/712414990442823761/2020-05-20_00h22_47.png)

![](https://cdn.discordapp.com/attachments/557122745931005967/712612159015616632/tkhtmlview_error.png)

**Comment by bauripalash** [comment]
Well , that's odd.
I have requirements set on https://github.com/bauripalash/tkhtmlview/blob/dde7e741231bb30cd6f434be3cb1a90dae06b1c7/setup.py#L24 
which https://packaging.python.org/discussions/install-requires-vs-requirements/ mentioned as preferred 

> install_requires is a setuptools setup.py keyword that should be used to specify what a project minimally needs to run correctly. When the project is installed by pip, this is the specification that is used to install its dependencies.

I don't understand, what's causing this 🤷‍♂️

**Comment by adsau59** [comment]
yeh, shouldn't it install the dependencies before running the `setup.py`

**Comment by bauripalash** [comment]
> yeh, shouldn't it install the dependencies before running the `setup.py`

That's supposed to happen. Is it something windows related? because i never tested tkhtmlview on windows!

**Comment by adsau59** [comment]
I'm not sure

**Comment by bauripalash** [comment]
Well , I'll look into it As soon as possible.

**Comment by dauptaia** [comment]
Same issue on my version , 
Python 3.8.5
PIL 7.2.0.

Darwin Cleopatre-MacBook-Air-CFD.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64

and same if I switch to the other side of the fork tk_html_widgets.

**Comment by dauptaia** [comment]
even weirder, my app opentea is also using PIL the same way as you., see https://gitlab.com/cerfacs/opentea3/-/blob/develop/src/opentea/gui_forms/node_widgets.py.

opentea Installation was working just fine before the dependency to tkhtmlview. Now it is going like :

```
_execfile(setup_script, ns)
  File "/usr/local/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-pknkdhks/tk_html_widgets-0.4.0/setup.py", line 2, in <module>
    # -*- encoding: utf-8 -*-
  File "/tmp/easy_install-pknkdhks/tk_html_widgets-0.4.0/tk_html_widgets/__init__.py", line 8, in <module>
  File "/tmp/easy_install-pknkdhks/tk_html_widgets-0.4.0/tk_html_widgets/html_parser.py", line 9, in <module>
ModuleNotFoundError: No module named 'PIL'
ERROR: Job failed: exit code 1
```

**Comment by bauripalash** [comment]
There's something sinister going on which I couldn't figure out yet.

**Comment by pozzolana93** [comment]
The error is due to the import of `tkhtmlview` in the setup.py, triggering the import of PIL which at that moment is not installed yet.
I think the package version information should be stored elsewhere. I am working on it

**Comment by jwaxy** [comment]
Is this fixed now. I am having the same error.

**Comment by simonepozzoli-pix4d** [comment]
@jwaxy I opened a PR some time ago, but the code owner still have to merge it. In the meanwhile you could pipi install this library from my pushed commit (https://pip.pypa.io/en/stable/topics/vcs-support/#supported-vcs)

**Comment by bauripalash** [comment]
My apologies. The notifications were pushed to bottom from the weight of other notifications. I have merged the PR mentioned. I think it should work fine now.

**Comment by xfornari** [comment]
Hi there, 
having Python 3.12, Pillow 10.2.0 (following the link form [tkinter](https://pypi.org/project/tk-html-widgets/), and ran into the very same problem?

@bauripalash: Is that actually published?

Thanks.

**Comment by bauripalash** [comment]
> Hi there, 
> having Python 3.12, Pillow 10.2.0 (following the link form [tkinter](https://pypi.org/project/tk-html-widgets/), and ran into the very same problem?
> 
> @bauripalash: Is that actually published?
> 
> Thanks.
> 

Can you show me the error?

**Comment by xfornari** [comment]
$pip list gives
...
pillow                        10.2.0
..
then:
$ pip install tk_html_widgets 1>tk_html.log 2>&1
which results in: [tk_html.log](https://github.com/bauripalash/tkhtmlview/files/14266253/tk_html.log)

**Comment by bauripalash** [comment]
@xfornari you're installing `tk_html_widgets` instead of `tkhtmlview`

**Comment by xfornari** [comment]
Well, I developed a while ago a small Python script that does not work any more:
```
$ python DDLD.pyw
Traceback (most recent call last):
  File "C:\ansysdev\Local\Home\Src\Python\pyddd\DDLD.pyw", line 11, in <module>
    from tk_html_widgets import HTMLScrolledText
ModuleNotFoundError: No module named 'tk_html_widgets'
```
Therefore I looked on PyPi for [tk_html_widgets](https://pypi.org/project/tk-html-widgets/)

Then:
`pip install tk-html-widgets`

which does not work...

I'll try tkhtmlview, which is a fork of the previous one..

**Comment by xfornari** [comment]
Works now with tkhtmlview. Thanks
