### ISSUE TITLE
Tkinter tkhtmlview Package

### ISSUE THREAD

**Issue by iamprakhar016** [bauripalash/tkhtmlview#4]
I am not able to see any color nor i am able to set color for select feature.

If a user selects any word or letter in html, i am able to get that word by selection_get() method, but i am not able to see or set color i.e. by default blue.

Another Problem is not able apply style which is put in head tag. Taking as a string and printing it.

code.txt

How to tackle it.
[code.txt](https://github.com/bauripalash/tkhtmlview/files/4742723/code.txt)

**Comment by bauripalash** [comment]
@iamprakhar016 , Unfortunately tkhtmlview doesn't yet support CSS styling. There's no way to tackle that.

**Comment by bauripalash** [comment]
Only a basic CSS is supported and there's not yet any API to get or set the color.

**Comment by lafkpages** [comment]
Some CSS does work, but it's very simple... I know that `color: red` works, but `color: rgb(255, 0, 0)` wont.

**Comment by lafkpages** [comment]
Also, at line `75` in `html_parser.py`, it says _BACKGROUD_COLOR_ instead of _BACKGROU**N**D_COLOR_. Maybe that caused some problems with backgrounds...

**Comment by bauripalash** [comment]
@lafkpages Fixed the typo
