### ISSUE TITLE
Issue pillow dependencies 

### ISSUE THREAD

**Issue by ViviLuD** [bauripalash/tkhtmlview#49]
Hello,

I'm having this issue:

Because no versions of tkhtmlview match >0.2.0,<0.3.0
 and tkhtmlview (0.2.0) depends on Pillow (>=9.4.0,<10.0.0), tkhtmlview (>=0.2.0,<0.3.0) requires Pillow (>=9.4.0,<10.0.0).
So, because hank depends on both pillow (^10.2.0) and tkhtmlview (^0.2.0), version solving failed.

The problem is that I can't downgrade pillow because when I try to install pillow 9.5.0 I have issues with the wheel.

Could you please fix this.

Thanks

**Comment by bauripalash** [comment]
I'll look into it ASAP

**Comment by bauripalash** [comment]
@ViviLuD I have pushed version 0.3.0, can you please try again and let me know if it works now?

**Comment by ViviLuD** [comment]
It works now, thanks ;)

**Comment by bauripalash** [comment]
> It works now, thanks ;)

Glas to know
